version: "3.1"

services:
  db:
    hostname: db
    container_name: db
    image: mongo
    restart: always
    ports:
      - 27017:27017
 
      
  dbui:
    hostname: dbui
    container_name: dbui
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8080:8081"
    depends_on:
      - db
   
  api:
    hostname: api
    container_name: api
    build:
      context: ./Backend
    ports:
      - 8000:8000
    depends_on:
      - db

  cliente:
    container_name: cliente
    build:
      context: ./Frontend
    ports:
      - 3001:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./Frontend:/app
      - ./Frontend/app/node_modules
    depends_on:
      - db
      - api